# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coletor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Coletores',
                'ordering': ['-nome'],
            },
        ),
        migrations.CreateModel(
            name='Determinação',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Determinadores',
                'ordering': ['-nome'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_exemplares', models.PositiveIntegerField(verbose_name='numero de exemplares')),
                ('comentarios', models.CharField(blank=True, max_length=30)),
                ('reino', models.CharField(blank=True, max_length=30)),
                ('filo', models.CharField(blank=True, max_length=50)),
                ('classe', models.CharField(blank=True, max_length=50)),
                ('ordem', models.CharField(blank=True, max_length=50)),
                ('familia', models.CharField(blank=True, max_length=50)),
                ('sub_familia', models.CharField(blank=True, max_length=50)),
                ('genero', models.CharField(blank=True, max_length=50)),
                ('especie', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('municipio', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('nome_rio', models.CharField(blank=True, max_length=50, verbose_name='nome do rio')),
                ('bacia_hidrografica', models.CharField(blank=True, max_length=50)),
                ('subbacia_hidrografica', models.CharField(blank=True, max_length=50)),
                ('data_coleta', models.DateField(verbose_name='data da coleta')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('publico', models.BooleanField()),
                ('projeto', models.CharField(max_length=50, null=True)),
                ('coletores', models.ManyToManyField(to='peixes.Coletor')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('determinadores', models.ManyToManyField(to='peixes.Determinação')),
            ],
            options={
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descrição', models.CharField(blank=True, max_length=30)),
                ('autorização', models.CharField(blank=True, max_length=50)),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projetos',
                'ordering': ['-nome'],
            },
        ),
        migrations.CreateModel(
            name='Tecido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(blank=True, max_length=50)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('musculo', models.BooleanField()),
                ('nadadeira', models.BooleanField()),
                ('inteiro', models.BooleanField()),
                ('outro', models.BooleanField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peixes.Lote')),
            ],
            options={
                'verbose_name_plural': 'Tecidos',
            },
        ),
    ]
