# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 22:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixes', '0015_auto_20170813_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projeto',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, size=None),
        ),
    ]
