# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixes', '0016_auto_20170813_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projeto',
        ),
        migrations.AddField(
            model_name='profile',
            name='projeto',
            field=models.ManyToManyField(to='peixes.Projeto'),
        ),
    ]
