# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-21 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peixes', '0018_auto_20171021_0338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'permissions': (('can_edit_lote', 'Can edit a lote of peixes'), ('can_delete_lote', 'Can delete a lote of peixes'), ('can_view_lote', 'Can edit a lote of peixes')), 'verbose_name_plural': 'Lotes'},
        ),
    ]
