# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-24 03:32
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peixes', '0021_auto_20171024_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='longitude',
        ),
        migrations.AddField(
            model_name='lote',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
