# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-25 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixes', '0022_auto_20171124_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='comentarios',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descrição',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
