# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-25 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixes', '0023_auto_20171124_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='curador',
            field=models.CharField(max_length=50),
        ),
    ]
