# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-26 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peixes', '0025_auto_20171130_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projeto',
            field=models.ManyToManyField(blank=True, to='peixes.Projeto'),
        ),
    ]
