# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-17 00:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peixes', '0026_auto_20171226_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peticoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.CharField(max_length=50)),
                ('lote', models.ManyToManyField(blank=True, to='peixes.Lote')),
                ('projeto', models.ManyToManyField(blank=True, to='peixes.Projeto')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Peticoes',
            },
        ),
    ]
